### PR TITLE
Added the ability for the enter key to be used...

### PR DESCRIPTION
**Pull request by kwdoyle**
...in addition to the plot button while the cursor is in any one of the three text-entry fields.

### CODE REVIEW

**Comment by zingale** [comment]
do you really need to replicate the whole _plot() function in __init__?  Can't you just bind to self._plot()?

**Comment by kwdoyle** [comment]
That's true, but then the _plot() would need to have two arguments in it for it to work. That is, it would have to be defined as _plot(self, event). If this is done, however, self.plot_button then breaks because, when the button is clicked, it gives an error stating that now _plot() requires two arguments when only one is given and I'm not sure how to get around that.

**Comment by kwdoyle** [comment]
Never mind, I think I found a solution.

**Comment by zingale** [comment]
this change gets it to work.

+        self.func.bind('<Return>', self._plot)
+        self.xmin.bind('<Return>', self._plot)
+        self.xmax.bind('<Return>', self._plot)
         
-    def _plot(self):
+    def _plot(self, event=None):

**Pull request merged**
